name = "terminal"
description = "Linux GLFW/Vulkan terminal emulator application"
version = "0.1.0-dev"
licenses = "MIT"
project-files = ["terminal.gpr"]

[[depends-on]]
terminal_common = "*"
terminal_core = "*"
terminal_pty = "*"
glfw_vulkan = "*"
df_vulkan = "*"
textrender = "*"
zlib = "*"

[[pins]]
terminal_common = { path = "terminal_common" }
terminal_core = { path = "terminal_core" }
terminal_pty = { path = "terminal_pty" }
glfw_vulkan = { path = "glfw_vulkan" }
textrender = { path = "../textrender" }
zlib = { path = "../zlib" }
