name = "terminal_glfw_vulkan_app"
description = "Linux GLFW/Vulkan terminal application"
version = "0.1.0-dev"
licenses = "MIT"

[[depends-on]]
terminal_common = "*"
terminal_core = "*"
terminal_pty_posix = "*"
glfw_vulkan = "*"
df_vulkan = "*"
textrender = "*"
zlib = "*"
aunit = "*"

[[pins]]
terminal_common = { path = "../terminal_common" }
terminal_core = { path = "../terminal_core" }
terminal_pty_posix = { path = "../terminal_pty_posix" }
glfw_vulkan = { path = "../glfw_vulkan" }
textrender = { path = "../../textrender" }
zlib = { path = "../../zlib" }
