name = "terminal_pty"
description = "Linux POSIX PTY backend for the Ada terminal"
version = "0.1.0-dev"
licenses = "MIT"

[[depends-on]]
terminal_common = "*"
aunit = "*"

[[pins]]
terminal_common = { path = "../terminal_common" }
